apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikubetask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minikubetask
  template:
    metadata:
      labels:
        app: minikubetask
    spec:
      containers:
      - name: minikubetask
        image: minikube:latest   
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: minikubetask-config
        - secretRef:
            name: minikubetask-secret
        volumeMounts:
        - mountPath: "/usr/share/nginx/html/data"
          name: minikubetask-storage
      volumes:
      - name: minikubetask-storage
        persistentVolumeClaim:
          claimName: minikubetask-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minikubetask-service
spec:
  type: NodePort
  selector:
    app: minikubetask
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
